//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporteAdiggm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Century, 8.25pt")]
        public global::System.Drawing.Font FuenteContDgv {
            get {
                return ((global::System.Drawing.Font)(this["FuenteContDgv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Century, 8.25pt, style=Bold")]
        public global::System.Drawing.Font FuenteTituloDgv {
            get {
                return ((global::System.Drawing.Font)(this["FuenteTituloDgv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195, 216, 247")]
        public global::System.Drawing.Color SeleccionarDgv {
            get {
                return ((global::System.Drawing.Color)(this["SeleccionarDgv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaptionText")]
        public global::System.Drawing.Color ColorFuenteDgv {
            get {
                return ((global::System.Drawing.Color)(this["ColorFuenteDgv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADIGGM;Initial Catalog=TransporteAdiggm;Persist Security Info=True;Us" +
            "er ID=sa;Password=ADIGGM*2016+;Application Name=TransporteAdiggm")]
        public string TransporteAdiggmConnectionString {
            get {
                return ((string)(this["TransporteAdiggmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=adiggm.hn;user id=adiggmhn_sa;database=adiggmhn_SAC;password=ADIGGM*2016+;" +
            "persistsecurityinfo=True")]
        public string adiggmhn_SACConnectionString {
            get {
                return ((string)(this["adiggmhn_SACConnectionString"]));
            }
        }
    }
}
